name: Turrets
main: iOTADevs\Turrets\Main
version: 1.0.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
load: STARTUP
author: iOTADevs
description: "[HALF-LIFE PORTALS] TURRETS!"
website: http://iotadevs.github.io
